### ISSUE TITLE
Can you provide examples of how to use methods in React?

### ISSUE THREAD

**Issue by SerendpityZOEY** [crubier/react-graph-vis#14]
Hi @crubier, do you know is there any way to use the methods in vis documentation in react?(http://visjs.org/docs/network/#options)

I added these methods (getSelectedNodes for example) like this, but seems not working. Can you provide an example where to put this code snippet in readme of this please?
```javascript
        var methods = {
            getSelectedNodes: function(node) {
                console.log('selected', node);
            },
        }
```
Thank you in advance.

**Comment by lrecknagel** [comment]
I think one way is to pass back the network instance from the Graph component via a callback.
I´ve also needed it and implemented it here: https://github.com/lrecknagel/react-graph-vis

**Comment by crubier** [comment]
Did #15 fix this ? It is merged and publish as [react-graph-vis@0.1.1](https://www.npmjs.com/package/react-graph-vis)

**Comment by SerendpityZOEY** [comment]
Hi @lrecknagel , thank you for your example. Your code helps me understand how to create an instance of network. I'm also facing some issue and want to modify the network instance. So I change the library from node_modules instead(but I don't think it's a good idea.). 

I saw your index.js is written in another way. So in this case I create a graph component on my own without import from node_modules right? Your solution seems a good idea.

**Comment by lrecknagel** [comment]
Hi @SerendpityZOEY , no you can use the current npm version and when you creating your Graph-Component eg: 

```js
return (
    <GraphVis
        getNetwork={this.setNetworkInstance}
        graph={graph} />
```

you pass the prop getNetwork as prop with a callback function in you current component which can be like:

```js
setNetworkInstance = nw => {
    this.network = nw;
};
```

Then you can use the it like:

```js
this.network. getSelectedNodes()
```

**Comment by typekev** [comment]
Hello @lrecknagel is your above mentioned solution valid for the current version of react-graph-vis?
I tested it out, but no success.

Thanks!

**Comment by lrecknagel** [comment]
Hello @typekev, it should work with the current version. It is in the code. Can you may should how you code looks like, I think then we can find the issue.

**Comment by typekev** [comment]
@lrecknagel Sorry for the long wait!

`      <Graph
        graph={this.state.graph}
        options={options}
      />`

options are the default options nothing special.

`    const options = {
      autoResize: true,
      height: '100%',
      width: '100%',
      interaction: {
        selectConnectedEdges: false,
        hoverConnectedEdges: true
      },
      manipulation: {
        enabled: true,
        initiallyActive: true,
        addNode: function (nodeData, callback) {
          nodeData = {
            id: Math.floor((Math.random() * 1000) + 1),
            value: Math.floor((Math.random() * 1000) + 1),
          };
          callback(nodeData);
        },
        addEdge: function (edgeData, callback) {
          if (edgeData.from === edgeData.to) {
            var r = confirm("Do you want to connect the node to itself?");
            if (r === true) {
              callback(edgeData);
            }
          }
          else {
            callback(edgeData);
          }
        }
      }
`

Besides that, I am not doing anything special.

**Comment by typekev** [comment]
This 

>         getNetwork={this.setNetworkInstance}

Does not seem to accomplish anything for me.

**Comment by lrecknagel** [comment]
And you´ve implemented **setNetworkInstance** like:

```js
setNetworkInstance = nw => {
    this.network = nw;
}
```

If have have it like this you then can as example do:

```js
// somewhere
this.network.getSelectedNodes()

// in a later called method ...
initStabilizationLoadingBar = () => {
    const _this = this;
    this.network.on('stabilizationProgress', function(params) {
        // do something with the progress ...
    });
}
```

**Comment by typekev** [comment]
Thanks very much for the advice @lrecknagel!

I am trying to create a pair of buttons that would allow me to create new nodes with unique characteristics on click.

Something along the lines of having one button to create a triangular node, and another button to create a dot node.

Do you have any examples of this use case with react-graph-vis?

**Comment by ateev** [comment]
Is this what you guys were looking for ? #32  ?

**Comment by kdog1425** [comment]
@typekev - what @lrecknagel suggested worked for me. Please see working example:
[GraphView.js](https://github.com/kdog1425/React-Redux-Flask-Web-Crawler/blob/master/static/src/components/GraphView.js)

**Comment by chepelevdi** [comment]
@kdog1425 thank you so much)

**Comment by typekev** [comment]
Thanks very much for the help everyone 😄 the project was successful.

**Comment by crubier** [comment]
Happy to hear the community solved it! 3 years later I'm late to the game haha

**Comment by sk8Guerra** [comment]
Is there a way to use the `fit` function to zoom in at a specific scale when rendering the `Graph` component from https://www.npmjs.com/package/react-graph-vis in react? I have not been able to understand how to use it.
