### ISSUE TITLE
Take DOT language as input

### ISSUE THREAD

**Issue by SerendpityZOEY** [crubier/react-graph-vis#20]
Hi @crubier , I'm using react-graph-vis as a npm package. I found out the only way to take DOT language as input is to modify the node_modules of react-graph-vis. It seems not a good solution to me. The problem is, if I modified the library, it can only take DOT and can't deal with JSON. I'm thinking can you add the option to either take JSON or take DOT?

In vis.js documentation, it is using 'vis.network.convertDot(DOTstring);' to convert DOT language to JSON if the input is DOT.

Thank you!

**Comment by crubier** [comment]
Hi, I do not have time to work on this feature, but I think it should be fairly easy to develop as you said. Feel free to make a pull request !
