### ISSUE TITLE
Graph size won't change if the properties are declared in percentile.

### ISSUE THREAD

**Issue by david921023** [crubier/react-graph-vis#24]
Hi,
I want to display my graph that is dynamically resizing according to the window size.
From options, even though I set the width and height properties to a certain percentile (ex: width: 100%), it won't do anything and will follow the default setting, which is,

`Graph.defaultProps = {
  graph: {},
  getNetwork: _react2.default.PropTypes.function,
  style: { width: '640px', height: '480px' }
};`

If I manually change the default property to,
`style: { width: '100%', height: '100%' }`
My intention works.
Can you please resolve this issue?
I really need your module for my react project.
Thanks a lot!

**Comment by crubier** [comment]
Did you try setting the `style` property of the component like this ?

```jsx
<Graph graph={graph} style={{ width: '100%', height: '100%' }}/>
```

**Comment by kadinwu** [comment]
@david921023 could you try set Graph options property as below to see if can fix your issue?
options={
    width: "100%",
    height: "100%",
    autoSize: true
}

**Comment by corganfuzz** [comment]
It works if you do viewport width, like this:

`<Graph graph={graph} style={{ width: '100vh', height: '100vh' }}/>`
