### ISSUE TITLE
Dataset Node Issues

### ISSUE THREAD

**Issue by victors1681** [crubier/react-graph-vis#33]
I was using "react-graph-vis": "0.1.1" and I was able to use Dataset Node like:

```
const  graph = {
                nodes: new vis.DataSet(),  
                edges: new vis.DataSet(),
            };

graph.nodes.add([
  {id: 1, text: 'item 1', date: new Date(2013, 6, 20), group: 1, first: true},
  {id: 2, text: 'item 2', date: '2013-06-23', group: 2},
  {id: 3, text: 'item 3', date: '2013-06-25', group: 2},
  {id: 4, text: 'item 4'}
]);

React.render(<Graph graph={graph} options={options} events={events} />, document.body);

```
After update to 0.1.3 it doesn't works.

**Comment by brysgo** [comment]
Hey @victors1681 - the way to do this in the new world is more of a react, declarative style, rather than with the graph vis imperative api. Now all you have to do is change the data that is passed through, and the chart will update accordingly.

**Comment by ObaidAshiq** [comment]
can u share an example of that?
What I am doing is that whenever I make change
I use network.setData({nodes:newModifiedNodes:edges:newModifiedEdges})
