### ISSUE TITLE
Passing extra props to graph

### ISSUE THREAD

**Issue by anorman1967** [crubier/react-graph-vis#34]
I'm trying to use the network to select nodes, and once a node is selected I want the event to execute a function in the parent component. 

normally, I would pass some extra prop to the child component (network in this case) and then within the child I could run the parent function.

from parent:

`<Graph graph={graph} options={options} events={events} myfunc={this.myfunc.bind(this)} />`

And then in the event in the graph I could call the myfunc

this.props.myfunc(event)

Is there a way to do this? I'm probably just missing something, or a better way to do it in general -- I'm relatively new to react..

**Comment by kaela** [comment]
You have to attach it to one of the events already available. For example:

```js
const events = {
   selectNode: (e) => {
      this.props.myfunc(e);
   }
}
```

And then when you call the component:

```js
<Graph graph={graph} 
       options={options} 
       events={events} />
```
