### ISSUE TITLE
warning "react-graph-vis@0.1.4" has incorrect peer dependency "react@^15.3.0"

### ISSUE THREAD

**Issue by onpaws** [crubier/react-graph-vis#36]
Any word on React 16 compatibility?
Seeing the above warning on app startup. 
If it's compatible (it seems to be in my app so far), could we please adjust the peer dep?

**Comment by crubier** [comment]
Fixed in cbe9fdd35f615949af23f5b74699e0e1735cc908    published `react-graph-vis@1.0.2`

**Comment by onpaws** [comment]
Great, thanks @crubier 👍
