### ISSUE TITLE
Version 1.0.2 - Issue on Vis - Cannot read property 'forEach' of null

### ISSUE THREAD

**Issue by jrrcdev** [crubier/react-graph-vis#39]
I got the error Cannot read property 'forEach' of null when using the 1.0.2, the 1.0.1 works fine.

Well, the Vis has this issue on versions after 4.18.1

The work around is to install the Vis@4.18.1 in your own project - npm install --save vis@4.18.1

I saw the react-graph-vis@1.0.2 is using the Vis@4.18.1, I don't know why the error if the version is the same
Just for you know about guys.

Thanks

**Comment by crubier** [comment]
v1.0.7 is using a much more recent of vis.js , should fix your problems !
