### ISSUE TITLE
Not Importing Correctly (with Webpack?)

### ISSUE THREAD

**Issue by allxie** [crubier/react-graph-vis#4]
Hey Crubier,
I've tried importing this about 6 different ways (your way, import Graph from 'react-graph-vis, import {Graph} from...etc.)  into my react code and failed to get this working until I copied your index.js code into a component of my own in my custom libs folder. I was getting the following errors:

Warning: Component(...): React component classes must extend React.Component.

and

Uncaught Invariant Violation: ReactCompositeComponent.render(): A valid ReactComponent must be returned. You may have returned undefined, an array or some other invalid object.

Thanks for the lib!

**Comment by desduvauchelle** [comment]
+1

**Comment by jurgob** [comment]
I'm using webpack and this is working. witch version of react are you using?

**Comment by crubier** [comment]
The issue seems to be fixed now. Create it again if this is needed !

**Comment by SerendpityZOEY** [comment]
@jurgob, @crubier Can you please give me an example of how you make it with webpack? I always getting the same error because of unexpected token import no matter I used 'require' or 'import' to import this package. Thanks in advance.
