### ISSUE TITLE
How can I add an edge like in native vis.js example

### ISSUE THREAD

**Issue by msjbear** [crubier/react-graph-vis#40]
When I  create an instance of network using react-graph-vis,  How can I add an edge like in native vis.js example via dragStart and dragEnd. [interactionEvents](http://visjs.org/examples/network/events/interactionEvents.html)

**Comment by crubier** [comment]
You can access the vis js Network instance in the `Network` attribute of the react component. This should allow you to do everything you want, the vis js way

**Comment by ozanilbey** [comment]
I couldn't get it. How can I reach the Network instance and activate addEdgeMode() here?

These are the related pieces of my code:

`import Graph from 'react-graph-vis';`
.
.
.
`<Graph graph={this.data} options={this.options} events={this.events} />`

**Comment by jsphweid** [comment]
@ozanilbey , basically like this: https://github.com/crubier/react-graph-vis/issues/49#issuecomment-392249018

**Comment by crubier** [comment]
We now do this in the example page (see homepage of this package, and follow link to source of the example:  https://github.com/crubier/react-graph-vis/tree/master/example/src/index.js
