### ISSUE TITLE
Tooltip example

### ISSUE THREAD

**Issue by sfbrunner** [crubier/react-graph-vis#41]
Hi crubier,
Thanks for the really great module.
Can I just ask for a quick example how to display a tooltip, for example onclick or onhover? How do you use the "events" object to do that?

Thanks a ton!
Simon

**Comment by rlyle** [comment]
Would love to see this as well.. I'm putting a "title" field into my nodes, but I can't get it to display the title when the mouse is hovering over the nodes.

**Comment by chepelevdi** [comment]
@rlyle Hi, have you found any solutions?

**Comment by rlyle** [comment]
@chepelevdi no we did not, I was able to hook the showPopup event and display a Snackbar from the bottom instead which was good enough.

**Comment by chepelevdi** [comment]
@rlyle I've resolved it. Solution: you have to connect vis-network.min.css directly to your project(to index.html or directly from modules/vis/.. to your component)

**Comment by mdhrumil** [comment]
@rlyle Can you please show me an example on how can you add a custom display such as Snackbar in your case, on showPopup event. I am not able to get it done. I'm trying to display a modal box.

**Comment by thechosenjuan** [comment]
I already added the vis-network.min.css to the component but still, the tooltip is not showing. @chepelevdi Did you did anything else to get it to work?

**Comment by thechosenjuan** [comment]
Managed to get it working. Thanks @chepelevdi !

**Comment by crubier** [comment]
@chepelevdi or @thechosenjuan if you have a working example, we could add it to the doc, that would be nice !

**Comment by thechosenjuan** [comment]
Sure, here's a working example:
https://codesandbox.io/embed/9y6v20p9wp?fontsize=14

**Comment by crubier** [comment]
Thanks ! Updated the readme

**Comment by fatlard1993** [comment]
`import 'vis-network/styles/vis-network.css';`

**Comment by Alternan** [comment]
> 
> 
> `import 'vis-network/styles/vis-network.css';`

awesome, only with this change in the import my problem was solved. I searched in several sites and this is the solution. Thanks for write it.
