### ISSUE TITLE
The mousemove/mouseenter/mouseleave events

### ISSUE THREAD

**Issue by septagram** [crubier/react-graph-vis#42]
Hello and thanks for a great library :)

I have a request. The `vis.js` doesn't provide these events, but probably because they are simple to implement when you can access the actual canvas DOM node and attach events to it (actually, the [methods](http://visjs.org/docs/network/#methodCanvas) for converting coordinates between the DOM and the graph are provided).

This is not the case in React, because the canvas node isn't so easily accessble. Accessing DOM nodes of a child component is hacky and might be deprecated eventually.

So could you please add those events? Or would you accept a pull request with those events added? These would help a lot in our use case, more fitting than the hover event.

**Comment by crubier** [comment]
I could still accept a PR for this :-)
