### ISSUE TITLE
Is it possible to use a custom component for the nodes?

### ISSUE THREAD

**Issue by barrymichaeldoyle** [crubier/react-graph-vis#51]
Hi there, thanks for the great package. However the documentation is a little bit limited. Is is possible to let a node use a custom component? That would be an absolutely amazing feature if not!

If it is possible, could anyone provide me with a little bit of guidance as to how I can implement it?

Thanks!

**Comment by barrymichaeldoyle** [comment]
Now how would I create a react root for every node exactly?

**Comment by brysgo** [comment]
I'm not sure it is possible since the library uses canvas (it may be possible if it were SVG or HTML), react would need to be rendering to something that vis.js understands, and I don't see any interactive capabilities.

**Comment by brysgo** [comment]
Maybe try [semiotic](https://emeeks.github.io/semiotic/#/semiotic/networkframe)

**Comment by aswinr92** [comment]
http://visjs.org/examples/network/nodeStyles/HTMLInNodes.html

Use like this, add <foreignObject> inside svg and add html inside that, then convert it to an image and use shape as 'image'.

**Comment by barrymichaeldoyle** [comment]
I saw that example but I couldn't find the source code for that :/

**Comment by aswinr92** [comment]
Right click - View page source :)

**Comment by barrymichaeldoyle** [comment]
Ah right, thanks.

**Comment by yogevlahyani** [comment]
Is there another solution that I can actually use a component?
