### ISSUE TITLE
Add GUI and events boilerplate? Can't link vis gui changes to parent component.

### ISSUE THREAD

**Issue by danielgmu** [crubier/react-graph-vis#52]
Vis js has a manipulation enabled option that adds a GUI to add nodes, edit nodes, add edges, delete, etc. I'm trying to link that up with the react-graph-vis component to make it more complete. Also trying to add the boilerplate for events. I'm close but need help as a new person to React. I currently can't link the changes happening from gui to the state in the parent component.

I would really appreciate some help. Thanks.

https://github.com/danielgmu/react-graph-vis-gui

**Comment by agustin107** [comment]
[https://stackoverflow.com/questions/42852571/activating-the-manipulation-system-in-react-graph-vis](Activating the manipulation system in react-graph-vis)

**Comment by crubier** [comment]
Indeed :-)
