### ISSUE TITLE
Source code to generate example shown in image?

### ISSUE THREAD

**Issue by neil-coles-m3** [crubier/react-graph-vis#54]
Do you have example code for generating the graph shown in the image?

**Comment by crubier** [comment]
Hi, this screenshot is an example from vis.js (without react). It i easy to run in react-graph-vis, just input the data from the vis-js example into the react-graph-vis example.

- The vis-js example: http://visjs.org/examples/network/exampleApplications/lesMiserables.html
- Code from the vis-js example: https://github.com/almende/vis/blob/master/examples/network/exampleApplications/lesMiserables.html
- Code example for react-graph-vis (just replace the data there with data from vis-js example) https://github.com/crubier/react-graph-vis/blob/master/example/src/index.js
