### ISSUE TITLE
Export to pdf

### ISSUE THREAD

**Issue by brezaie** [crubier/react-graph-vis#61]
Hi pals,

Is it possible to export the graph to pdf or png or any other image formats?

Thanks

**Comment by crubier** [comment]
It is rendered on a canvas so you can export the canvas content.

```javascript
var canvas = document.getElementById("mycanvas");
var img    = canvas.toDataURL("image/png");
```

**Comment by conor909** [comment]
strange I just get a blank black image with no errors
