### ISSUE TITLE
Change visjs dependency

### ISSUE THREAD

**Issue by segfault16** [crubier/react-graph-vis#66]
almende/vis is being deprecated: https://github.com/almende/vis/issues/4259

The network component of visjs lives on here: https://github.com/visjs-community/visjs-network

Current version is v4.23.3.

I propose changing the dependency to `visjs-network`.

**Comment by mojoaxel** [comment]
`almende/vis` is now maintained by the community: www.visjs.org
I would recommend switching to the official successor [vis.network](https://github.com/visjs/vis-network)
