### ISSUE TITLE
Missing new version

### ISSUE THREAD

**Issue by ynahmany** [crubier/react-graph-vis#69]
Hi
the lib has been updated while ago to use visjs-network instead of vis, yet a newer version has not been published to npm. 
Is there any time estimation for that?

**Comment by crubier** [comment]
I can do that next week !

**Comment by ynahmany** [comment]
great!!! 
Thanks a lot!

**Comment by ynahmany** [comment]
Any update ? :)

**Comment by jaredrada** [comment]
Would be great to have this new version published to npm!

**Comment by ynahmany** [comment]
It was fixed and pushed to npm.
Thanks!
