### ISSUE TITLE
rename to react-vis-network

### ISSUE THREAD

**Issue by mojoaxel** [crubier/react-graph-vis#70]
I would recommend renaming this library to something network specific like "react-vis-network". This way it is more clear, that this library is only supporting network charts.

_Also: Please consider adding this library here: https://github.com/visjs/awesome-visjs#visjs-based-libraries_

**Comment by crubier** [comment]
Thank you, someone already added this lib to https://github.com/visjs/awesome-visjs#visjs-based-libraries .

And yes the name could be changed. I'll do it when I'll publish v2.0 of this lib ;-)

**Comment by sakshampandey-mern** [comment]
which command we using to start this example project in our local?
