### ISSUE TITLE
Update vis-network to version 6

### ISSUE THREAD

**Issue by kovalchuk-vyacheslav** [crubier/react-graph-vis#78]
Current version of this package uses version 5 of vis-network. However in version 6 there are a lot of improvements which I'm not able to use now. 

So can u update this package to version 6?

**Comment by mkarimv** [comment]
I have the same request.

**Comment by whitewolf92** [comment]
why no update to 7? lol

**Comment by hesto2** [comment]
I created a fork and published it to npm with some minor bug fixes and updates in it that I plan on maintaining for my company (which relies on this library). I just updated it to v6.5.2 and everything appears to be working as expected. Upgrading to v7 had some breaking changes so I haven't implemented that one yet. If you want to give it a go, here is the link:
https://github.com/hesto2/react-vis-network-graph

**Comment by hesto2** [comment]
As a side note, this has now been upgraded to v7:
https://github.com/hesto2/react-vis-network-graph

**Comment by xn3cr0nx** [comment]
Thank you @hesto2, I'm using your version. I was looking for a bugfix, but it doesn't seem to fix it anyway. Maybe do you know why nodes are not redrawn after graph updates? I have a node of some color under some conditions, then the graph is updated and the node should come back to default color, but it seems redraw is not triggered, even if I explicitly call it on the network instance.

**Comment by hesto2** [comment]
I've had a few different similar issues with edges. I think vis-network
doesn't handle removing value very well. For example, if I update a node to
have an opacity of 1 and then later update that node to have an opacity of
undefined it will still keep the original value on there. Are you maybe
running into something similar with the default color here?

**Comment by xn3cr0nx** [comment]
@hesto2 yes I think we are talking about the same problem. I would expect it to work at least forcing redraw, but it doesn't seem to work. If I check nodes in network object I can see color property is no more applied to the node, but the change doesn't reflect on the ui.

**Comment by hesto2** [comment]
Can you create an issue with your details here and I'll try and spend some
time and figure it out as soon as possible:
https://github.com/hesto2/react-vis-network-graph/issues

**Comment by tomaszburda** [comment]
Any ideas about version 8 ?

**Comment by crubier** [comment]
Done, we are now using version 9
