### ISSUE TITLE
Node tooltip does not show up

### ISSUE THREAD

**Issue by MosMK** [crubier/react-graph-vis#79]
The class vis-tooltip should have position absolute to be shown.
I could pull a request if you want to.

**Comment by karldahlgren** [comment]
Hi @MosMK!
I was also struggling with this issue recently, but I managed to solve it by including the vis.min.css in my index.html file.

```
<link href="https://cdnjs.cloudflare.com/ajax/libs/vis/4.21.0/vis.min.css" rel="stylesheet" type="text/css" />

I hope that this solves your issue.
Best regards,
Karl Dahlgren

**Comment by crubier** [comment]
Indeed, same as https://stackoverflow.com/questions/42852571/activating-the-manipulation-system-in-react-graph-vis
