### ISSUE TITLE
Cannot use react-graph-vis with typescript

### ISSUE THREAD

**Issue by Pacheco95** [crubier/react-graph-vis#80]
I'm trying to use the lib in a TS project, but I'm getting this error:
`Could not find a declaration file for module 'react-graph-vis'`
I tried `yarn add @types/react-graph-vis` but yarn tell me type definitions does not exists for this lib.

Any way to solve this issue?

```typescript
import React, { useState } from 'react';
import Graph from 'react-graph-vis';

const graph = {
  nodes: [
    { id: 1, label: 'Node 1', color: '#e04141' },
    { id: 2, label: 'Node 2', color: '#e09c41' },
    { id: 3, label: 'Node 3', color: '#e0df41' },
    { id: 4, label: 'Node 4', color: '#7be041' },
    { id: 5, label: 'Node 5', color: '#41e0c9' },
  ],
  edges: [
    { from: 1, to: 2 },
    { from: 1, to: 3 },
    { from: 2, to: 4 },
    { from: 2, to: 5 },
  ],
};

const options = {
  layout: {
    hierarchical: false,
  },
  edges: {
    color: '#000000',
  },
};

const events = {
  select(event) {
    const { nodes, edges } = event;
    console.log('Selected nodes:');
    console.log(nodes);
    console.log('Selected edges:');
    console.log(edges);
  },
};

const Home = () => {
  const [network, setNetwork] = useState(null);

  return (
    <div className="Home">
      <Graph
        graph={graph}
        options={options}
        events={events}
        getNetwork={(networ: any) => {
          //  if you want access to vis.js network api you can set the state in a parent component using this property
          setNetwork(network);
        }}
      />
    </div>
  );
};

export default Home;

```

**Comment by carlosaicrag** [comment]
instead of "import Graph from 'react-graph-vis" try "import Graph from 'vis-react' "

**Comment by dtseng123** [comment]
It is because there isn't a type declaration file. 
A workaround is to add a declaration to your  _typings.d.ts_ file.

`declare module "react-graph-vis";`

**Comment by ChadJPetersen** [comment]
I'm pretty new to Typescript. So not sure if this is the best way to define the module. But this has been working well for me!

https://gist.github.com/ChadJPetersen/2e2587bbd753c6a384c02519183e2031

**Comment by strican** [comment]
Would be cool if this could be published as a `@types/react-graph-vis` package.

**Comment by Karim-rebey** [comment]
Hi, I'm trying to add the react-graph-vis feature to my application and I don't know where to put the new configuration.

**Comment by vignesh-sleeksky** [comment]
Can someone please tell me the procedures on how to use this file.
